# Path to save location for logs
LOGS_PATH: "logs/account_monitor_logs.log"

# Path to save location for state
SAVE_STATE_PATH: "state/account_monitor.json"

# Path to save location for state (in seconds)
SAVE_INTERVAL: 1800 # 30 minutes

# Health score bounds for min/max update interval frequency
HS_LOWER_BOUND: 1.05
HS_UPPER_BOUND: 2.0

# Update interval frequency (in seconds)
MIN_UPDATE_INTERVAL: 10
MAX_UPDATE_INTERVAL: 1200 # 20 minutes

# Interval for reporting low health accounts
LOW_HEALTH_REPORT_INTERVAL: 3600 # 6 hours
SLACK_REPORT_HEALTH_SCORE: 10

# Threshold for excluding small positions from frequent notifications, in USD terms
SMALL_POSITION_THRESHOLD: 10000000000000000000 # 10 USD
SMALL_POSITION_REPORT_INTERVAL: 21600 # 6 hours

# Bath size for scanning blocks on startup
BATCH_SIZE: 10000
BATCH_INTERVAL: 0.1

# Time to wait between scanning on regular intervals
SCAN_INTERVAL: 120 # 2 minutes

# Settings for 1INCH Quoting & other API calls
NUM_RETRIES: 3
RETRY_DELAY: 10

# Acceptable amound of overswapping of collateral for 1INCH binary search
SWAP_DELTA: .01 # 1%
MAX_SEARCH_ITERATIONS: 20
API_REQUEST_DELAY: 1

# EVC Deployment Block
EVC_DEPLOYMENT_BLOCK: 238643655

# Addresses of relevant contracts
WETH: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"

EVC: "0xE45Ee4046bD755330D555dFe4aDA7839a3eEb926"

ORACLE_LENS: "0xC07235265101E9F6510a8ce92Cf358413E066d9e"
SWAPPER: "0xD36C60B1ae52E78601C85542e40e81B27df4ED1C"
SWAP_VERIFIER: "0x8aAA2CaEca30AB50d48EB0EA71b83c49A2f49791"

LIQUIDATOR_CONTRACT: "0xceba76639F653E1C2adeEbD79e67506961bEe6f1"

PYTH: "0xff1a0f4744e8582DF1aE09D5611b887B6a12925C"

# Receiver of profits
PROFIT_RECEIVER: "0xeC5DF17559e6E4172b82FcD8Df84D425748f6dd2" #TODO change to DAO address

# Compiled contract paths
EVAULT_ABI_PATH: "contracts/EVault.json"
EVC_ABI_PATH: "contracts/EthereumVaultConnector.json"
LIQUIDATOR_ABI_PATH: "out/Liquidator.sol/Liquidator.json"
ORACLE_ABI_PATH: "contracts/IOracle.json"
PYTH_ABI_PATH: "contracts/IPyth.json"
ERC20_ABI_PATH: "out/IERC20.sol/IERC20.json"

# Chain ID
CHAIN_ID: 42161